### ISSUE TITLE
Add plutil(1)

### ISSUE THREAD

**Issue by Artoria2e5** [gnustep/libs-base#101]
Since its introduction in Mac OS X 10.2, many users of the said system have started to seen plutil(1) as the only plist command-line editor. plutil(1) is a program that does most of pldes(1) and friend does, but all put in one tool. Around macOS 10.15, plutil(1) seems to have received a lot of editing capabilities that are not found in online manpages.

I am currently working on a version of plutil for GNUstep, sans the programming language and JSON literal features for now. This issue is really just for a future pull request reference.

plutil(1) manpage in macOS 10.14: https://www.unix.com/man-page/mojave/1/plutil
plutil(1) manpage in macOS 10.15: [plutil.1.gz](https://github.com/gnustep/libs-base/files/4218369/plutil.1.gz)

* * *
A related utility found on macOS but not yet in GS is PlistBuddy. Both utilities have a MIT/Expat licensed C++ implementation by Facebook at https://github.com/facebook/xcbuild/tree/master/Libraries/plist/Tools. I am mainly writing plutil(1) from scratch for the new 10.15 features.

**Comment by rfm** [comment]
Contribution now merged.
