### ISSUE TITLE
NSLocale/general.m tests fail with ICU 65

### ISSUE THREAD

**Issue by doko42** [gnustep/libs-base#103]
seen when building with ICU 65:

base/NSLocale/general.m:
Failed test:       general.m:26 ... NSLocaleIdentifier key returns 'es_ES@currency=ESP'
Failed test:       general.m:38 ... NSLocaleVariantCode key returns nil
Failed test:       general.m:59 ... NSLocaleCurrencySymbol key returns 'xx3'
Failed test:       general.m:62 ... NSLocaleCurrencyCode key returns 'ESP'
Failed test:       general.m:65 ... NSLocaleCollatorIdentifier for Spain

esting general.m...
Running base/NSLocale/general.m...
Start set:       general.m:14 ... NSLocale
Failed test:       general.m:26 ... NSLocaleIdentifier key returns 'es_ES@currency=ESP'
Expected 'es_ES@currency=ESP' and got 'es_ES_PREEURO'
Passed test:       general.m:29 ... NSLocaleLanguageCode key returns 'es'
Passed test:       general.m:32 ... NSLocaleCountryCode key returns 'ES'
Passed test:       general.m:36 ... NSLocaleScriptCode key returns nil
Failed test:       general.m:38 ... NSLocaleVariantCode key returns nil
Expected '(null)' and got 'PREEURO'
Passed test:       general.m:40 ... NSLocaleCollationIdentifier key returns nil
Passed test:       general.m:42 ... NSLocaleExemplarCharacterSet key returns a NSCharacterSet
Passed test:       general.m:45 ... NSLocaleCalendar key returns a NSCalendar
Passed test:       general.m:48 ... NSLocaleUsesMetricSystem key returns a NSNumber
Passed test:       general.m:50 ... NSLocaleUsesMetricSystem key returns YES
Passed test:       general.m:52 ... NSLocaleMeasurementSystem key returns 'Metric'
Passed test:       general.m:55 ... NSLocaleDecimalSeparator key returns ','
Failed test:       general.m:59 ... NSLocaleCurrencySymbol key returns 'xx3'
Expected '₧' and got '€' (unicode codepoint 8364)
Failed test:       general.m:62 ... NSLocaleCurrencyCode key returns 'ESP'
Expected 'ESP' and got 'EUR'
Failed test:       general.m:65 ... NSLocaleCollatorIdentifier for Spain
Expected 'es_ES@currency=ESP' and got 'es_ES_PREEURO'

do these just need updating expected test results?

**Comment by fredkiefer** [comment]
No, as you can see the results in the test match the values in the Travis tests, on the few platforms where these still work. I get the same values as you (OpenSuse Tumbleweed)
Maybe we need a switch in this tests to allow for both versions?

**Comment by fredkiefer** [comment]
I just found this bug report on ICU https://unicode-org.atlassian.net/browse/ICU-20187#icft=ICU-20187. Looks like they dropped support for these old names two years ago. We either remove them as well or add support for the mapping in base itself. Not sure which is the correct approach.

**Comment by xnox** [comment]
Well spain has not used ₧ for ages now. And there is little value in testing spanish locales pre 1st of January 1999, which is 20 years ago.

The code also has this comment
```
  // These tests don't really work all that well.  I need to come up with
  // something better.  Most of the ones that fail are because nil is returned.
  locale = [[NSLocale alloc] initWithLocaleIdentifier: @"es_ES_PREEURO"];
```

But doesn't say why es_ES_PREEURO was chosen, and why shouldn't we update the expected values to new ones, or like even update the locale to use modern EURO based ES locale.

**Comment by xnox** [comment]
```
--- gnustep-base-1.26.0.orig/Tests/base/NSLocale/general.m
+++ gnustep-base-1.26.0/Tests/base/NSLocale/general.m
@@ -22,7 +22,7 @@ int main(void)
 
   // These tests don't really work all that well.  I need to come up with
   // something better.  Most of the ones that fail are because nil is returned.
-  locale = [[NSLocale alloc] initWithLocaleIdentifier: @"es_ES_PREEURO"];
+  locale = [[NSLocale alloc] initWithLocaleIdentifier: @"es_ES@currency=ESP"];
   PASS_EQUAL([locale objectForKey: NSLocaleIdentifier],
     @"es_ES@currency=ESP",
     "NSLocaleIdentifier key returns 'es_ES@currency=ESP'");
```

Seems to work for me, but I don't know if the test was specifically to test that locale canonilization with translation happens correctly. Because now the requested locale, matches the canonicalized name.

**Comment by markusicu** [comment]
FYI more background info on the ICU 64 change is in the ICU 64 API proposal doc:
https://docs.google.com/document/d/1ryrKsC5a_dhlkTTA6HBZzcoMpeLAXt2RcbLUyTSSW4g/edit#heading=h.d38o60d1p2y4
"[approved:2018-11-14] remove obsolete locale ID canonicalization mappings"

**Comment by fredkiefer** [comment]
I just checked on MacOSX and there the lines

`    NSLocale *locale = [[NSLocale alloc] initWithLocaleIdentifier: @"es_ES_PREEURO"];
    NSLog(@"identifier %@", [locale objectForKey: NSLocaleIdentifier]);
`

result in the output 

`identifier es_ES@currency=ESP`

This means Apple supports these old specifiers. It would be better if we keep support for them, which would require another mapping level in NSLocale. At least if a newer version of ICU gets detected.

**Comment by fredkiefer** [comment]
I was able to resolve this issue by adding the following line to the file Locale.canonical:

  ca_ES_PREEURO = "ca_ES@currency=ESP";
  de_AT_PREEURO = "de_AT@currency=ATS";
  de_DE_PREEURO = "de_DE@currency=DEM";
  de_LU_PREEURO = "de_LU@currency=LUF";
  el_GR_PREEURO = "el_GR@currency=GRD";
  en_BE_PREEURO = "en_BE@currency=BEF";
  en_IE_PREEURO = "en_IE@currency=IEP";
  es_ES_PREEURO = "es_ES@currency=ESP";
  eu_ES_PREEURO = "eu_ES@currency=ESP";
  fi_FI_PREEURO = "fi_FI@currency=FIM";
  fr_BE_PREEURO = "fr_BE@currency=BEF";
  fr_FR_PREEURO = "fr_FR@currency=FRF";
  fr_LU_PREEURO = "fr_LU@currency=LUF";
  ga_IE_PREEURO = "ga_IE@currency=IEP";
  gl_ES_PREEURO = "gl_ES@currency=ESP";
  it_IT_PREEURO = "it_IT@currency=ITL";
  nl_BE_PREEURO = "nl_BE@currency=BEF";
  nl_NL_PREEURO = "nl_NL@currency=NLG";
  pt_PT_PREEURO = "pt_PT@currency=PTE";
  de__PHONEBOOK = "de@collation=phonebook";
  es__TRADITIONAL = "es@collation=traditional";
  hi__DIRECT = "hi@collation=direct";
  ja_JP_TRADITIONAL = "ja_JP@calendar=japanese";

Somebody has to decide whether this is an acceptable change.

**Comment by rfm** [comment]
I'm inclined to think that the Locale.canonical change is the correct fix.
That's based on the information that OSX is returning es_ES@currency=ESP as the local identifier,  which, as far as I can see, is what OSX considers to be the canonical version.

**Comment by fredkiefer** [comment]
Should I apply that change or are you going to do that?

**Comment by rfm** [comment]
I can do that. Thanks.

**Comment by fredkiefer** [comment]
Should be fixed by this commit https://github.com/gnustep/libs-base/commit/5248b6ee363f1da256297182aff7579fb614c535
