### ISSUE TITLE
NSString/test08.m tests fail with ICU 65

### ISSUE THREAD

**Issue by doko42** [gnustep/libs-base#104]
base/NSString/test08.m:
Failed test:     test08.m:47 ... 11 is greater than 2
Failed test:     test08.m:61 ... numeric sort

Testing test08.m...
Running base/NSString/test08.m...
Passed test:     test08.m:27 ... 1 is less than 2
Passed test:     test08.m:32 ... 1 is less than 10
Passed test:     test08.m:37 ... 1 is less than 11
Passed test:     test08.m:42 ... 11 is greater than 1
Failed test:     test08.m:47 ... 11 is greater than 2
Passed test:     test08.m:56 ... text sort
Failed test:     test08.m:61 ... numeric sort
Expected '(1, 2, 3, 10, 11, 20)' and got '(1, 10, 11, 2, 20, 3)'
Completed file:  test08.m

**Comment by fredkiefer** [comment]
I get the same results on my OpenSuse Tumbleweed. Looks like ICU requires different values there. I never got around to inspect this.
What OS are you using?

**Comment by doko42** [comment]
that's trying to build the Ubuntu packages:
https://launchpad.net/ubuntu/+source/gnustep-base/1.26.0-6build3

**Comment by fredkiefer** [comment]
I started this pull request  https://github.com/gnustep/libs-base/pull/109 which fixes the issue for me locally. Could you please give it a try and comment on the pull request?

**Comment by rfm** [comment]
Closing due to lack of feedback
