### ISSUE TITLE
-[NSArray indexOfObject: inSortedRange: options:0 usingComparator:] raises range exception when object is not found

### ISSUE THREAD

**Issue by zneak** [gnustep/libs-base#11]
The following very simple program raises an index error:

```objc
#import <Foundation/Foundation.h>

int main() {
        NSArray* ints = @[@(1), @(2)];
        [ints indexOfObject:@(3) inSortedRange:NSMakeRange(0,2) options:0 usingComparator:^(id left, id right) { 
                int diff = [left intValue] - [right intValue];
                if (diff < 0) return NSOrderedAscending;
                if (diff > 0) return NSOrderedDescending;
                return NSOrderedSame;
        }];
}
```

```shell
$ ./obj/index
./obj/index: Uncaught exception NSRangeException, reason: Index 2 is out of range 2 (in 'objectAtIndex:')
```

It seems to happen because [NSArray.m:1211](https://github.com/gnustep/libs-base/blob/master/Source/NSArray.m#L1207) assumes that `GSLeftInsertionPointForKeyInSortedRange` returns an index within the collection.

**Comment by ivucica** [comment]
@zneak Does this still happen?

**Comment by ivucica** [comment]
Apologies, I see that this is a very recent (September 2017) submission.

@rfm Any thoughts?

**Comment by rfm** [comment]
> It seems to happen because NSArray.m:1211 assumes that GSLeftInsertionPointForKeyInSortedRange returns an index within the collection.

I agree ... the code is not checking for the case where the insertion point for the key would be at the end of the array before attempting to find out if the object at the insertion point is equal to he key.  I added a simple check for that case.
