### ISSUE TITLE
GNUstep.conf in wrong location on FreeBSD

### ISSUE THREAD

**Issue by snunez1** [gnustep/libs-base#117]
Guessing this is the right repository to report this issue.

GNUstep.conf is located in /usr/local/GNUstep/ when installed via FreeBSD packages. It seems likely that this should actually be /usr/local/etc/GNUstep/

**Comment by rfm** [comment]
That is an issue for the FreeBSD package maintainer.
The gnustep-make package makes the location of GNUstep.conf,  but it is up to the maintainers of a particular distribution to decide where they want it in their distribution.
