### ISSUE TITLE
NSJSONSerialization serializes all integral NSNumbers as signed numbers

### ISSUE THREAD

**Issue by zneak** [gnustep/libs-base#12]
Per https://github.com/gnustep/libs-base/blob/master/Source/NSJSONSerialization.m#L944:

```objc
  else if ([obj isKindOfClass: NSNumberClass])
    {
      const char        *t = [obj objCType];

      if (strchr("cCsSiIlLqQ", *t) != 0)
        {
          long long     i = [(NSNumber*)obj longLongValue];

          [output appendFormat: @"%lld", i];
        }
      else
        {
          [output appendFormat: @"%.17g", [(NSNumber*)obj doubleValue]];
        }
    }
```

Regardless of whether the `NSNumber` has been created a signed or unsigned variant of `numberWith(sign)(size)`, it'll be JSON-serialized as an unsigned number. This is a problem, because negative numbers can be equal to positive numbers mostly only in C-family languages, and JSON interops with much higher-level languages.

**Comment by iamleeg** [comment]
I have a fix for this but to test it would like to use `ULLONG_MAX` from `limits.h`, which is a C99 header. Does gnustep still support compiler versions where that would be a problem?
