### ISSUE TITLE
Unable to change NSFileModificationDate to '2019-06-28 19:35:09 -0400' - Not a directory, English.lproj/MainMenu.nib 

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-base#151]
NSFileManager method:

```
- (BOOL) copyItemAtPath: (NSString*)src
		 toPath: (NSString*)dst
		  error: (NSError**)error

```

Is failing to copy nib files in buildtool because of this error...

2020-07-09 01:31:59.997 buildtool[1221:1221]    ERROR: Unable to change NSFileModificationDate to '2019-06-28 19:35:09 -0400' - Not a directory, English.lproj/MainMenu.nib -> build/Bean/Products/Bean.app/Resources/English.lproj/MainMenu.nib

I don't believe that this should be preventing the copy operation to finish.  Updating the creation date should not be a critical failure.

**Comment by gcasa** [comment]
It is not copying items in the subdirectories of any of the resources.

**Comment by rfm** [comment]
I changed the code to refrain from attempting to set the creation/modification date of the new copy to that of the original:  the new copy should have dates set to the instant when the copy occurred.

**Comment by gcasa** [comment]
Confirmed.  This is working fine... thank you.
