### ISSUE TITLE
Compilation failure on Windows

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-base#155]
Compiling file NSFileCoordinator.m ...
 Compiling file NSFileHandle.m ...
NSFileCoordinator.m: In function '-[NSFileCoordinator coordinateAccessWithIntents:queue:byAccessor:]':
NSFileCoordinator.m:156:7: warning: passing argument 1 of 'blockOperationWithBlock:' from incompatible pointer type [enabled by default]
NSFileCoordinator.m:156:7: note: expected 'GSBlockOperationBlock' but argument is of type 'GSAccessorCallbackHandler'
 Compiling file NSFileManager.m ...
 Compiling file NSFileVersion.m ...
NSFileManager.m: In function '-[NSFileManager changeFileAttributes:atPath:]':
NSFileManager.m:584:29: error: '_S_IFDIR' undeclared (first use in this function)
NSFileManager.m:584:29: note: each undeclared identifier is reported only once for each function it appears in
NSFileManager.m:591:19: warning: unused variable 'ti' [-Wunused-variable]
NSFileManager.m: At top level:
NSFileManager.m:2575:3: error: unknown type name '_WDIR'
NSFileManager.m: In function 'gsedRelease':
NSFileManager.m:2585:3: warning: implicit declaration of function '_wclosedir' [-Wimplicit-function-declaration]
NSFileManager.m: In function '-[NSDirectoryEnumerator initWithDirectoryPath:recurseIntoSubdirectories:followSymlinks:justContents:skipHidden:errorHandler:for:]':
NSFileManager.m:2638:7: error: unknown type name '_WDIR'
NSFileManager.m:2654:7: warning: implicit declaration of function '_wopendir' [-Wimplicit-function-declaration]
NSFileManager.m:2654:19: warning: assignment makes pointer from integer without a cast [enabled by default]
NSFileManager.m: In function '-[NSDirectoryEnumerator nextObject]':
NSFileManager.m:2806:16: warning: implicit declaration of function '_wreaddir' [-Wimplicit-function-declaration]
NSFileManager.m:2806:34: warning: initialization makes pointer from integer without a cast [enabled by default]
NSFileManager.m:2809:22: error: dereferencing pointer to incomplete type
NSFileManager.m:2888:12: error: 'S_IFDIR' undeclared (first use in this function)
NSFileManager.m:2888:24: error: 'S_IFMT' undeclared (first use in this function)
NSFileManager.m:2890:5: error: unknown type name '_WDIR'
NSFileManager.m:2893:7: warning: assignment makes pointer from integer without a cast [enabled by default]
NSFileManager.m: In function '-[GSAttrDictionary filePosixPermissions]':
NSFileManager.m:3876:30: error: 'S_IFMT' undeclared (first use in this function)
NSFileManager.m: In function '-[GSAttrDictionary fileType]':
NSFileManager.m:4034:29: error: 'S_IFMT' undeclared (first use in this function)
NSFileManager.m:4036:12: error: 'S_IFREG' undeclared (first use in this function)
NSFileManager.m:4037:12: error: 'S_IFDIR' undeclared (first use in this function)
NSFileManager.m:4038:12: error: 'S_IFCHR' undeclared (first use in this function)
NSFileManager.m:4039:12: error: 'S_IFBLK' undeclared (first use in this function)
NSFileManager.m:4043:12: error: 'S_IFIFO' undeclared (first use in this function)
NSFileManager.m:4049:1: warning: control reaches end of non-void function [-Wreturn-type]
NSFileManager.m: In function '-[GSAttrDictionary filePosixPermissions]':
NSFileManager.m:3877:1: warning: control reaches end of non-void function [-Wreturn-type]
make[4]: *** [obj/libgnustep-base.obj/NSFileManager.m.o] Error 1
make[4]: *** Waiting for unfinished jobs....
 Compiling file NSFileWrapper.m ...
make[3]: *** [internal-library-all_] Error 2
make[2]: *** [libgnustep-base.all.library.variables] Error 2
make[1]: *** [internal-all] Error 2
make: *** [internal-all] Error 2
This is gnustep-make 2.8.0. Type 'make print-gnustep-make-help' for help.
Running in gnustep-make version 2 strict mode.
rm -rf ./*~ ./obj
Making clean in Source ...
rm -rf ./*~ ./obj
rm -f libgnustep-gui.def
Making clean in Images ...
rm -rf ./*~ ./obj
Making clean in Sounds ...
rm -rf ./*~ ./obj
Making clean in Model ...

**Comment by gcasa** [comment]
I will attach logs ASAP...

**Comment by fredkiefer** [comment]
Could you please explain your system a bit more? According to Travis GNUstep base still compiles on the two systems we are currently testing with.

**Comment by gcasa** [comment]
Sorry I haven't been fast with returning to this.  I have been hospitalized over the last couple of days.

**Comment by gcasa** [comment]
I am using MINGW32_NT.    The script i am using to build is windows-build in tools-scripts.

**Comment by gcasa** [comment]
This was due to the "make distclean" I had in the script.
