### ISSUE TITLE
It is currently not possible to use non-strings as keys...

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-base#157]
Steps to recreate...
1) Create an NSArray
2) Create an NSDictionary
3) use the NSArray as a key for something in the NSDictionary.

Result: you will get an exception complaining about hasPrefix: (this is called in NSDictionary.m) to remove "@" from the string...
EXPECTED: This should work.

Please see my example test here: https://github.com/gcasa/NSDictionary_test

**Comment by rfm** [comment]
Using non-strings as keys seems to work fine under most circumstances.
It seems in this case -valueForKey: is being called with a non-string argument (the method prototype says the argument must be a string), so the problem would appear to be in whatever part of your code is calling -valueForKey: (of course that call is likely to be indirect).
We could change -valueForKey: to check that its argument is really a string, but it might be better to identify and correct whatever is calling it.

**Comment by gcasa** [comment]
I believe the code which is causing the issue is calling -valueForKey:.  This should work if I'm not mistaken.  I will modify my test to show this better.

**Comment by gcasa** [comment]
Nevermind... tested it on cocoa....  I get this...
```
2020-09-26 15:40:22.113861-0400 NSDictionary_test[5953:1246750] -[__NSSingleObjectArrayI length]: unrecognized selector sent to instance 0x600000004cb0
2020-09-26 15:40:22.114333-0400 NSDictionary_test[5953:1246750] -[__NSSingleObjectArrayI length]: unrecognized selector sent to instance 0x600000004cb0
```
This is undefined behavior... so we should just leave it as is.  I am glad this prompted you to add a test to make sure we could use an array as a key.   The user who did this has been informed that this is not proper usage. :)  Thanks, GC
