### ISSUE TITLE
NSStream should not require subclasses to implement streamError

### ISSUE THREAD

**Issue by lcampbel** [gnustep/libs-base#181]
Apple's documentation says the only methods required to be implemented by subclasses are:

NSInputStream: read:maxLength:, getBuffer:length:, and hasBytesAvailable
NSOutputStream: write:maxLength: and hasSpaceAvailable

streamError is not on either of these lists, so NSStream should provide a stub that returns nil.

**Comment by rfm** [comment]
Maybe there's conflicting documentation,  but I think you are probably looking at the documentation for the *additional* methods that subclasses of NSInputStream and NSOutputStream must provide.
I think the methods that a subclass must provide are also those documented explicitly as required for NSStream:
https://developer.apple.com/documentation/foundation/nsstream

**Comment by lcampbel** [comment]
Ah, ok, right you are. Thanks!
