### ISSUE TITLE
gnustep-base 1.28.0 triggers a regression in sogo

### ISSUE THREAD

**Issue by landryb** [gnustep/libs-base#212]
cf https://www.sogo.nu/bugs/view.php?id=5416 for more details, on OpenBSD 7.0 i've found out that gnustep-base 1.28.0 triggers a wrong behaviour in sogo where xml content gets encoded from ICS content served by the database. This breaks end-users not being able to see events they just created from thunderbird and pushed to SOGo.

working curl caldav request with gnustep-base 1.27.0 gives:
```
...
<D:propstat><D:prop><C:calendar-data>BEGIN:VCALENDAR
...
END:VCALENDAR</C:calendar-data><D:getetag>&quot;gcs00000000&quot;</D:getetag>...
```
with gnustep-base 1.28.0 this gives:
```
<D:propstat><D:prop><C:calendar-data>&#65279;BEGIN:VCALENDAR
...
END:VCALENDAR</C:calendar-data><D:getetag>&#65279;&quot;gcs00000000&quot;</D:getetag>
```
note the extra `&#65279;` which is an xml-encoded representation of the UTF8 BOM character. I'm not sure where the gnustep-base code is called from SOGo, but i know it's a regression from the gnustep-base upgrade.

**Comment by fredkiefer** [comment]
@rfm could you please have a look here? I am a bit confused on what is actually going on here.
While looking at the change that seems to cause all this, I noticed that the optimisation for the dataUsingEncoding: method is only present for the constant string class, not for the other ones. Was that on purpose? This should be unrelated to this issue, as the code in NSString looks correct to me.

**Comment by ivucica** [comment]
(Drive-by comment: It seems like this would be grounds for adding a minimum unit test demonstrating the expected behavior, so we don't break this in the future..)

**Comment by fredkiefer** [comment]
@ivucica you are correct. The problem is just that we don't know what features of NSString SOGo is using here.

**Comment by fredkiefer** [comment]
@rfm this is a tests whether you now get mails for bug reports. Your help here is appreciated.

**Comment by rfm** [comment]
Well, it appears likely that something is putting a BOM in a string and that's then being output as utf-8, but we really need to find out where.  I agree that a unit test to reproduce it would be good.
NB. The only BOM related changes I recall in the last year or two were making gnustep-base behavior consistent with OSX behavior when converting to/from encodings, so ideally we need a testcase that can be run on OSX as well as on gnustep , to see where any problem is.

**Comment by rfm** [comment]
The place to look is the code generating that vcard.  Perhaps it does something like converting bits of the vcard to NSData objects using NSUnicodeStringEncoding (which will produce a BOM at the start of each NSData object), then concatenating the NSData objects, then creating a string with embedded BOMs?  Alternatively, perhaps in gnustep-base there is something that works like that somewhere?  Either way, looking at the SoGo code generating the vcard string is a good starting point to see what is happening.

**Comment by SlavekB** [comment]
In Alinto/sogo#324, there is a patch that looks good and solves the problem on the SOGo side.

**Comment by landryb** [comment]
fwiw, with sogo 5.8.0 i've tested that Alinto/sogo#324 properly fixed the issue i was seeing, so i'd close this issue as "not a gnustep-base regression" :) thanks !
