### ISSUE TITLE
NSURL prematurely releases it's NSURLHandle in the code path handling a loading fail

### ISSUE THREAD

**Issue by svgol** [gnustep/libs-base#235]
The method **-[NSURLHandle backgroundLoadDidFailWithReason:]** implicitly releases the NSURLhandle when cleaning its own registry of _clients and later tries to removes itself as a client  from the now deallocated handle:

```
2003    - (void) URLHandle: (NSURLHandle*)sender
2004      resourceDidFailLoadingWithReason: (NSString*)reason
2005    {
2006      id    c = clientForHandle(_clients, sender);
2007
2008      if (c != nil)
2009        {
2010          if ([c respondsToSelector:
2011            @selector(URL:resourceDidFailLoadingWithReason:)])
2012            {
2013              [c URL: self resourceDidFailLoadingWithReason: reason];
2014            }
2015          [clientsLock lock];
2016          NSMapRemove((NSMapTable*)_clients, (void*)sender);   // <======== implicit release of the sender
2017          [clientsLock unlock];
2018        }
2019      [sender removeClient: self];   // <===== use of the now deallocated sender
2020    }

```
It doesn't pose any problem if the autorelease pool which retained the handle initially when the current URL loading began is around. If the retaining pool has gone in the middle it causes  a segfault. The same problem possibly exists in the **-[URLHandleResourceDidCancelLoading]**. 
Interestingly the **-[URLHandleResourceDidFinishLoading:]** calls **-[sender removeClient: self]** before cleaning of the _clients.

I has a feed in Grr which temporarily became problematic: allowed to connect but failed by a connection timeout. It is where I spotted the problem. The attached test case tries to replay the conditions leading to it.

[test03.zip](https://github.com/gnustep/libs-base/files/7971802/test03.zip)

**Comment by rfm** [comment]
I have changed the code so that all three methods should behave the same way (thread and retain/release safe).
Please let me know if that's OK.

**Comment by svgol** [comment]
Yes, the segfault has gone.

**Comment by rfm** [comment]
Thanks.
