### ISSUE TITLE
GSICUString.h:3:10: Fatal Error: unicode/utext.h: No such file or directory

### ISSUE THREAD

**Issue by abhi-varma202** [gnustep/libs-base#236]
Hi, I'm new to using gnustep base. I'm trying build source code with MSYS2 MinGW 64bit shell to generate 64 bit DLL's. I was successfully able to configure and make gnustep-make. I was also able to configure gnustep-base but when trying to run make while compiling its showing the following error.

```
Compiling file GSICUString.m ...
In file included from GSICUString.m:27:
GSICUString.h:3:10: fatal error: unicode/utext.h: No such file or directory
    3 | #include <unicode/utext.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/mingw64/share/GNUstep/Makefiles/rules.make:521: obj/libgnustep-base.obj/GSICUString.m.o] Error 1
make[3]: *** [/mingw64/share/GNUstep/Makefiles/Instance/library.make:292: internal-library-all_] Error 2
make[2]: *** [/mingw64/share/GNUstep/Makefiles/Master/rules.make:297: libgnustep-base.all.library.variables] Error 2
make[1]: *** [/mingw64/share/GNUstep/Makefiles/Master/library.make:37: internal-all] Error 2
make: *** [/mingw64/share/GNUstep/Makefiles/Master/serial-subdirectories.make:53: internal-all] Error 2

```
I have checked there is no utext.h file inside unicode folder in source code or is it planning to take it from somewhere else? i have seen a unicode folder with utext.h file present in "C:\msys64\usr\include\unicode" is it supposed to take from here

**Comment by rfm** [comment]
> On 8 Feb 2022, at 04:46, Sai Abhishek Varma K ***@***.***> wrote:
> 
> 
> Hi, I'm new to using gnustep base. I'm trying build source code with MSYS2 MinGW 64bit shell to generate 64 bit DLL's. I was successfully able to configure and make gnustep-make. I was also able to configure gnustep-base but when trying to run make while compiling its showing the following error.
> 
> Compiling file GSICUString.m ...
> In file included from GSICUString.m:27:
> GSICUString.h:3:10: fatal error: unicode/utext.h: No such file or directory
>     3 | #include <unicode/utext.h>
>       |          ^~~~~~~~~~~~~~~~~
> compilation terminated.
> make[4]: *** [/mingw64/share/GNUstep/Makefiles/rules.make:521: obj/libgnustep-base.obj/GSICUString.m.o] Error 1
> make[3]: *** [/mingw64/share/GNUstep/Makefiles/Instance/library.make:292: internal-library-all_] Error 2
> make[2]: *** [/mingw64/share/GNUstep/Makefiles/Master/rules.make:297: libgnustep-base.all.library.variables] Error 2
> make[1]: *** [/mingw64/share/GNUstep/Makefiles/Master/library.make:37: internal-all] Error 2
> make: *** [/mingw64/share/GNUstep/Makefiles/Master/serial-subdirectories.make:53: internal-all] Error 2
> 
> 
> I have checked there is no utext.h file inside unicode folder in source code or is it planning to take it from somewhere else?

The utext.h file comes from the mingw ICU package ... it should be found among the headers installed by that package.
Possibly there is a version of icu where the header is missing?

**Comment by triplef** [comment]
From the line numbers it looks like you’re on an older revision of libs-base. I’d try building the latest master branch, where this import is guarded by `HAVE_UNICODE_UTEXT_H`:

https://github.com/gnustep/libs-base/blob/e9ed77fb680505070be94fef3f70fb548fe6df3d/Source/GSICUString.h#L4-L6
