### ISSUE TITLE
NSPredicate beginswith throws NSRangeException when strings are too short

### ISSUE THREAD

**Issue by anthonyc-r** [gnustep/libs-base#243]
The following example code outputs this:
`2022-03-07 09:44:16.470 nspredicate_test[11580:11580] Exeption: <NSException: 0x557970c11d90> NAME:NSRangeException REASON:in compare:options:range:locale:, range { 0, 3 } extends beyond size (2) INFO:(null)
2022-03-07 09:44:16.470 nspredicate_test[11580:11580] Strings: (a, aa, aaa, aaaa)`

`#import <Foundation/Foundation.h>

int main(int argc, char **argv) {
	NSAutoreleasePool *pool = [NSAutoreleasePool new];

	NSMutableArray *strings = [NSMutableArray arrayWithObjects: @"a", @"aa",
		@"aaa", @"aaaa", nil];
	NSPredicate *beginsWithPredicate = [NSPredicate predicateWithFormat:
		@"self beginswith 'aaa'"];
	@try {
		[strings filterUsingPredicate: beginsWithPredicate];
	}
	@catch (NSException *ex) {
		NSLog(@"Exeption: %@", ex);
	}
	NSLog(@"Strings: %@", strings);

	[pool release];
	return 0;
}`

Whereas trying this xcode 2.5/OSX 10.4 simply rejects the entries which are too short, as expected. I can see there are a couple of NSPredicate-related tickets open, but this seemed like a separate issue. Cheers.

**Comment by rfm** [comment]
Thanks for that very clear report.
I have committed a fix to the repository.

**Comment by anthonyc-r** [comment]
Thank you for the quick response and fix
