### ISSUE TITLE
GSObjCRuntime.m: fatal error: 'pthread.h' file not found

### ISSUE THREAD

**Issue by abhi-varma202** [gnustep/libs-base#244]
I'm trying to compile GSObjCRuntime.m file using Visual Studio clang-cl but its throwing me the following error.
```
GSObjCRuntime.m(732,10): fatal error: 'pthread.h' file not found
#include <pthread.h>
         ^~~~~~~~~~~
```
I understand that using Unix like environments (like Cygwin) would compile with pthread.h. But when working with vs clang-cl compiler how to make it work?

**Comment by triplef** [comment]
You seem to be building an older version of libs-base. Please update to the latest master revision, which will be using native Windows threading APIs (https://github.com/gnustep/libs-base/commit/abfe4e2a0413d5acaca46c997d7676997f4252c1).
