### ISSUE TITLE
Redefining NSConnection Class During Compilation

### ISSUE THREAD

**Issue by abhi-varma202** [gnustep/libs-base#246]
I have recently come across a mac code where in the makefile they are redefining the class name of NSConnection with MYConnection during compilation using the compiler option like as follows

```
-DNSConnection=MYConnection
```

and during debugging I saw that whenever ``` [NSConnection class] ``` is called its returning a Class of type ```MYConnection```

isn't -D option only used for defining a macro?
How come its changing the class type when calling ```[NSConnection class]``` to ```MYConnection```?
Doing the same will work on windows as well?

**Comment by triplef** [comment]
`-D` just set a preprocessor define, same as this:
```c
#define NSConnection MYConnection
```

With this set, every time the preprocessor encounters `NSConnection` in your code, it will replace it with `MYConnection`, before the code is compiled.

Hope that helps.
