### ISSUE TITLE
making gnu step look like mac

### ISSUE THREAD

**Issue by alavaelian** [gnustep/libs-base#248]
in the web site says that gnustep can look like mac but i cannot acces to learn more so i was wondering if someone can help me to get the amazing look of mac in gnustep

**Comment by anthonyc-r** [comment]
You can grab a theme such as this:
https://github.com/AlessandroSangiuliano/rik.theme
Once installed, this can be set to active in the system preferences app, or via user defaults.

Then, enable client side decorations, to let GNUstep handle drawing the window borders, in a terminal run:
`defaults write NSGlobalDomain GSBackHandlesWindowDecorations YES`
And set it to use a single global top menu:
`defaults write NSGlobalDomain NSInterfaceStyleDefault NSMacintoshInterfaceStyle`
I think the above two items can also be found under defaults of the system preferences app too.

To get the dock, you can use GWorkspace, it has some configuration options that let you select the semi-transparent 'modern' style. 

A few notes; The window decoration theming only applies to GNUstep applications, and if a GNUstep app isn't active, the top menu will disappear.
