### ISSUE TITLE
Cannot Configure - Error "checking whether objc really works"

### ISSUE THREAD

**Issue by adderthorn** [gnustep/libs-base#253]
I am having trouble compiling `base` on openSUSE. I've setup `libobjc2` and `make` and am using `clang` as the compiler. `base` is failing on "Checking whether objc really works" with the following found in "config.log"

```
configure:8215: checking whether objc really works
configure:8235: clang -o conftest -g -O2  -I/usr/GNUstep/Local/Library/Headers -I/usr/GNUstep/Local/Library/Headers -I/usr/GNUstep/System/Library/Headers  -x objective-c  -L/usr/GNUstep/Local/Library/Libraries -L/usr/GNUstep/Local/Library/Libraries -L/usr/GNUstep/System/Library/Libraries conftest.c -lrt -ldl  -lpthread -pthread -fexceptions -rdynamic -fobjc-runtime=gnustep-1.8 -fblocks -L/home/xxxx/GNUstep/Library/Libraries -L/usr/GNUstep/Local/Library/Libraries -L/usr/GNUstep/System/Library/Libraries -lpthread -lobjc -lm   -lpthread  >&5
In file included from conftest.c:106:
In file included from ././config/config.objc.m:2:
././config/objc-common.g:54:3: warning: assignment to Objective-C's isa is deprecated in favor of object_setClass() [-Wdeprecated-objc-isa-usage]
  obj->isa = self;
  ^  ~~~~~~~
  object_setClass( , )
././config/objc-common.g:47:5: note: instance variable is declared here
 id isa;
    ^
1 warning generated.
/usr/bin/ld: /tmp/conftest-4045ad.o: in function `main':
conftest.c:(.text+0x66): undefined reference to `objc_msgSend'
clang-14.0: error: linker command failed with exit code 1 (use -v to see invocation)
configure:8235: $? = 1
configure: program exited with status 1
```

I've tried playing with the make installer since I have a feeling I've just configured something wrong there, but haven't had much luck. For reference these are the args I used when configuring make:

```
./configure --with-layout=gnustep --disable-importing-config-file --enable-native-objc-exceptions --enable-objc-arc --enable-install-ld-so-conf --with-library-combo=ng-gnu-gnu --with-config-file=/usr/GNUstep/Local/Configuration/GNUstep.conf
```

**Comment by rfm** [comment]
> On 3 Aug 2022, at 23:56, Noah Wood ***@***.***> wrote:
> 
> 
> I am having trouble compiling base on openSUSE. I've setup libobjc2 and make and am using clang as the compiler. base is failing on "Checking whether objc really works" with the following found in "config.log"
> 
> configure:8215: checking whether objc really works
> configure:8235: clang -o conftest -g -O2  -I/usr/GNUstep/Local/Library/Headers -I/usr/GNUstep/Local/Library/Headers -I/usr/GNUstep/System/Library/Headers  -x objective-c  -L/usr/GNUstep/Local/Library/Libraries -L/usr/GNUstep/Local/Library/Libraries -L/usr/GNUstep/System/Library/Libraries conftest.c -lrt -ldl  -lpthread -pthread -fexceptions -rdynamic -fobjc-runtime=gnustep-1.8 -fblocks -L/home/xxxx/GNUstep/Library/Libraries -L/usr/GNUstep/Local/Library/Libraries -L/usr/GNUstep/System/Library/Libraries -lpthread -lobjc -lm   -lpthread  >&5
> In file included from conftest.c:106:
> In file included from ././config/config.objc.m:2:
> ././config/objc-common.g:54:3: warning: assignment to Objective-C's isa is deprecated in favor of object_setClass() [-Wdeprecated-objc-isa-usage]
>   obj->isa = self;
>   ^  ~~~~~~~
>   object_setClass( , )
> ././config/objc-common.g:47:5: note: instance variable is declared here
>  id isa;
>     ^
> 1 warning generated.
> /usr/bin/ld: /tmp/conftest-4045ad.o: in function `main':
> conftest.c:(.text+0x66): undefined reference to `objc_msgSend'
> clang-14.0: error: linker command failed with exit code 1 (use -v to see invocation)
> configure:8235: $? = 1
> configure: program exited with status 1
> 
> I've tried playing with the make installer since I have a feeling I've just configured something wrong there, but haven't had much luck. For reference these are the args I used when configuring make:
> 
> ./configure --with-layout=gnustep --disable-importing-config-file --enable-native-objc-exceptions --enable-objc-arc --enable-install-ld-so-conf --with-library-combo=ng-gnu-gnu --with-config-file=/usr/GNUstep/Local/Configuration/GNUstep.conf

It looks like you have two objc runtimes installed but the one in your default location is the wrong one as the library doesn't contain the right symbols (conftest.c:(.text+0x66): undefined reference to `objc_msgSend')

To fix that, you should be able to use the libobjc_CFLAGS and libobjc_LIBS environment variables when configuring gnustep-make, to pass it the flags to tell it where to find the headers and the library of libobjc2
gnustep-make will record that information so that, when you then configure gnustep-base, the script knows where to look for the headers/library

**Comment by adderthorn** [comment]
Thank-you! That was it. I had a version of libobjc installed via zypper that was causing issues. Instead of specifying the GNUstep one manually, I just removed the other package, reconfigured make and I am now up and running. Thanks for your help!
