### ISSUE TITLE
Why is NSOperationQueue limited to 8 real threads?

### ISSUE THREAD

**Issue by wbardwel** [gnustep/libs-base#263]
In the implementation there is a limit of the real thread pool
`#define	POOL	8`
This means that any code that uses NSOperationQueue on a CPU with lots of threads or with code that is doing lots of blocking operations in their NSOperation's can't get at all of their machines resources with a single NSOperationQueue.

Further the maxConcurrentOperationCount value is documented as setting the maximum number of operations that can be concurrent, but really that is POOL in this implementation.  Obviously someone can just edit the source to increase that hard coded limit, but I was wondering if there is some goal here other than trying to keep the caller safe from excess threads?

Also curious that the default maxConcurrentOperationCount is set to 200.  I would be happy with the thread max defaulting to 8, but being overridden by maxConcurrentOperationCount when it is reset to something other than the default.

**Comment by rfm** [comment]
I believe the limit was set for OSX compatibility, with tests showing that on OSX no more than 8 operations actually ran concurrently irrespective of the maxConcurrentOperationCount setting.
I think I agree that there's no strong reason we shouldn't allow more though (particularly as more modern hardware supports multiple threads more effectively).

**Comment by rfm** [comment]
See git repository for changed code relaxing the limit.

**Comment by wbardwel** [comment]
That change looks great, thanks.
