### ISSUE TITLE
NSDirectoryEnumerator incorrectly returns paths instead of URLs for `-[NSFileManager enumeratorAtURL:...]`

### ISSUE THREAD

**Issue by triplef** [gnustep/libs-base#292]
The NSDirectoryEnumerator returned from `-[NSFileManager enumeratorAtURL:...]` should be returning NSURL items from `-nextObject` as [documented](https://developer.apple.com/documentation/foundation/nsfilemanager/1409571-enumeratoraturl?language=objc#), but it currently returns NSString paths.

I’m not sure what would be the best way to refactor/fix this, any ideas? This might also be a good opportunity to annotate NSDirectoryEnumerator with generics.

**Comment by rfm** [comment]
Should be fixed in git master

**Comment by triplef** [comment]
Thank you!
