### ISSUE TITLE
Please use pkg-config to detect icu

### ISSUE THREAD

**Issue by hughmcmaster** [gnustep/libs-base#31]
`icu-config` has been deprecated by its upstream developers for some years now. In icu 63.1, `icu-config` is optional to install, but installed by default. In the next version, `icu-config` will no longer be installed by default.

The developers recommend downstream packages use `pkg-config` to detect the icu libraries.

Please let me know if you need any help with this change.

**Comment by ivucica** [comment]
Merged PR #32 in 8637bce8dcbde6a69e09cf38b892b61f84a8e082.
