### ISSUE TITLE
NSLock throws an exception when trying to unlock when not previously locked...

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-base#316]
Issue: NSLock throws an exception when trying to unlock when not previously locked...

Steps:
1) Create an NSLock / NSConditionLock
2) Try to unlock the instance without previously locking it.

Result: An exception is thrown, as illustrated by the attached image
Expected: This should either fail silently or log a warning...
![NSConditionLock_error](https://github.com/gnustep/libs-base/assets/27943/987cebcb-ff55-451f-9bcb-9a1eb11fae13)

**Comment by gcasa** [comment]
The test is here... https://github.com/gcasa/NSConditionLock_test

**Comment by hmelder** [comment]
What is the behaviour on macOS? I would consider unlocking before locking a programmer error.

**Comment by gcasa** [comment]
> What is the behaviour on macOS? I would consider unlocking before locking a programmer error.

The behavior on macOS is to simply ignore it.  I think out behavior is better but we should allow it to be configurable so a default was added. 

If merged a pr related to this with code from @rfm so I am closing this.
