### ISSUE TITLE
NSException.m:1450:7: error: '_objc_unexpected_exception' undeclared

### ISSUE THREAD

**Issue by sagitter** [gnustep/libs-base#319]
Hi all.

`gnustep-base-1.29.0` is not compiling in `Fedora 38 x86_64` with `GCC-13.2.1`:

```
gcc NSHashTable.m -c \
      -MMD -MP -DGNUSTEP_TARGET_DIR=\".\" -DGNUSTEP_TARGET_CPU=\"x86_64\" -DGNUSTEP_TARGET_OS=\"linux-gnu\" -DGNUSTEP_IS_FLATTENED=\"yes\" -DLIBRARY_COMBO=\"gnu-gnu-gnu\" -DGNUSTEP_BASE_INTERNAL=1 -Wall -Wdeclaration-after-statement -Wcast-align -DGNUSTEP -DGNUSTEP_BASE_LIBRARY=1 -DGNU_RUNTIME=1 -DGNUSTEP_BASE_LIBRARY=1 -fno-strict-aliasing -fexceptions -fobjc-exceptions -D_NATIVE_OBJC_EXCEPTIONS -pthread -fPIC -Wall -DGSWARN -DGSDIAGNOSE -Wno-import -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fcommon -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fconstant-string-class=NSConstantString -I../Headers -I./. -I. -I/home/sagitter/GNUstep/Library/Headers -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include/libxml2 -I/usr/include/libxml2 -I/usr/include/p11-kit-1 \
       -o obj/libgnustep-base.obj/NSHashTable.m.o
NSException.m: In function '+[NSException initialize]':
NSException.m:1450:7: error: '_objc_unexpected_exception' undeclared (first use in this function)
 1450 |       _objc_unexpected_exception = callUncaughtHandler;
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~
NSException.m:1450:7: note: each undeclared identifier is reported only once for each function it appears in
gmake[4]: *** [/usr/lib64/GNUstep/Makefiles/rules.make:521: obj/libgnustep-base.obj/NSException.m.o] Error 1
gmake[4]: *** Waiting for unfinished jobs....
NSFileManager.m: In function '-[NSFileManager changeFileAttributes:atPath:]':
NSFileManager.m:461:21: warning: ignoring return value of 'chown' declared with attribute 'warn_unused_result' [-Wunused-result]
  461 |               (void)chown(lpath, -1, pw.pw_gid);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
gmake[3]: *** [/usr/lib64/GNUstep/Makefiles/Instance/library.make:286: internal-library-all_] Error 2
```

[config_log.zip](https://github.com/gnustep/libs-base/files/12541327/config_log.zip)

**Comment by hmelder** [comment]
I am not familiar with the GNUstep GCC toolchain but here a quick analysis:

It is probably related to this:
https://github.com/gnustep/libs-base/blob/5f92c87d784753c996e14e4c75af7464014b6833/configure.ac#L2243

As there is no actual configuration check testing whether native exceptions are supported.

_objc_unexpected_exception is a hook for defining an exception handler. In this case this is [callUncaughtHandler](https://github.com/gnustep/libs-base/blob/5f92c87d784753c996e14e4c75af7464014b6833/Source/NSException.m#L1421). This hook was removed from the GCC Objective-C Runtime back in 2011 (https://github.com/gcc-mirror/gcc/blob/63663e4e69527b308687c63bacb0cc038b386593/libobjc/ChangeLog#L617).

As "_objc_unexpected_exception" is not present in the libobjc header, it is undeclared.

@rfm Are you familiar with exception handling on GCC?

**Comment by hmelder** [comment]
If possible, try to ditch GCC for Clang + libobjc2, as the Objective-C support is better and you have all the nice Objective-C 2.0 features.

**Comment by hmelder** [comment]
But for now, try to disable native Objective-C exceptions and see if that helps :)

**Comment by rfm** [comment]
configure.ac checks for the presence of _objc_unexpected_exception ... it was found at configure time.
It's not clear why it's not being found at compile time.
Possibly the configure test is including a header that NSException.m isnt.
Or possibly the library is being built with a different version of the runtime than the one it was configured for.

**Comment by rfm** [comment]
Closing due to lack of follow-up and the fact that, rather than a bug, this appears to be a case of configuring the base library using an older version of the runtime, then compiling using a more recent runtime.
