### ISSUE TITLE
NSISO8601DateFormatter generates noncompliant strings

### ISSUE THREAD

**Issue by kevinpeizner** [gnustep/libs-base#340]
The `NSISO8601DateFormatter` class generates date strings that are not compliant with the ISO8601 specification when the format option `NSISO8601DateFormatWithColonSeparatorInTimeZone` is used.

This option is used when specifying the formatting option `NSISO8601DateFormatWithInternetDateTime` which is also used by default.

A fix for this issue can be found here: https://github.com/gnustep/libs-base/pull/339

**Comment by rfm** [comment]
Should be working now, thanks.
