### ISSUE TITLE
Speedup CI by using prebuild debian packages

### ISSUE THREAD

**Issue by hmelder** [gnustep/libs-base#342]
We can install gnustep-make, libobjc2, and libdispatch from binary packages instead of building them with every CI run, speeding up the CI for Debian-based runners.

**Comment by triplef** [comment]
Personally I’d at least keep keep gnustep-make as a source dependency to ensure any changes there don’t cause issues here in the CI. It also doesn’t take long to build.

**Comment by hmelder** [comment]
That makes sense. Looking at the running times, the biggest bottleneck are the Windows workflows. Maybe we can ship libobjc2, libdispatch, and other auxiliary dependencies (minus gnustep-make) in binary form. It is not a priority, but I will leave this issue open.

**Comment by rfm** [comment]
That sounds good to me too.

**Comment by hmelder** [comment]
Debian packaging is just archaic and a pain to work with. I'll not put more effort in trying to package GNUstep for Debian.
