### ISSUE TITLE
Notes for next Release (1.30.0)

### ISSUE THREAD

**Issue by hmelder** [gnustep/libs-base#348]
Here are some notes of things we need to keep in mind when writing the Release Notes:

- Be aware of potential ABI incompatibility resulting from a signature alteration in NSObject's setVersion: method.
- Changes in dependencies:
   - Added libavahi and zlib as official requirements (See #320)
   - libxslt is now RECOMMENDED instead of OPTIONAL

**Comment by qmfrederik** [comment]
Are you targeting a specific date for the 1.30.0 release?  The latest release is ~1 year old at this point in time.

**Comment by gcasa** [comment]
Just tagging both @fredkiefer (gui maintainer) and @rfm (base maintainer) in this conversation since this question is relevant to their respective positions.  Release scheduling is entirely up to them.

**Comment by rfm** [comment]
At the last meeting we decided to aim for a release in March.

**Comment by qmfrederik** [comment]
That's great to hear, thanks!

**Comment by buzzdeee** [comment]
can be closed?
