### ISSUE TITLE
-[NSArray filteredArrayUsingPredicate:] should ignore NSNull values

### ISSUE THREAD

**Issue by triplef** [gnustep/libs-base#349]
The following code runs fine on Apple platforms and filters for the second array entry, but with GNUstep it raises an exception `Unable to find value for key "key" of object <null> (NSNull)`:

```objc
NSArray *array = @[@{@"key": @"value1"}, @{@"key": @"value2"}, NSNull.null];
NSArray *filtered = [array filteredArrayUsingPredicate:[NSPredicate predicateWithFormat:@"key == %@", @"value2"]];
NSLog(@"array: %@", array);
NSLog(@"filtered: %@", filtered);
```

**Comment by hmelder** [comment]
This boils down to how we handle KVCoding with NSNull.

Given this test program:
```objc
#import <Foundation/Foundation.h>

int main(void) {
  id obj = [[NSNull null] valueForKeyPath: @"key"];
  NSLog(@"Output: %@", obj);
  return 0;
}
```

The following is returned on macOS: 2023-12-09 19:32:08.434 a.out[6427:263545] Output: <null>
While on Debian with GNUstep:

<img width="1945" alt="image" src="https://github.com/gnustep/libs-base/assets/45601940/af5214e5-a7c6-48be-bfa5-03feb79a8cb3">

**Comment by hmelder** [comment]
Fixed it by overwriting valueForUndefinedKey in NSNull to avoid triggering the default handler which results in an exception.

I think Apple is doing the same thing.

**Comment by hmelder** [comment]
Fixed with https://github.com/gnustep/libs-base/pull/358

**Comment by triplef** [comment]
Thank you for the fix!
