### ISSUE TITLE
Windows 2000 experience.

### ISSUE THREAD

**Issue by fsb4000** [gnustep/libs-base#36]
Hello.

Stated that the previous version works on Windows 2000

http://www.gnustep.org/windows/installer.html

I managed build current release version gnustep on Windows 2000.

https://imgur.com/a/0yIvjoj

(gnustep-make-2.7.0
gnustep-base-1.26.0
gnustep-gui-0.27.0
gnustep-back-0.27.0
plugins-themes-WinUXTheme-master)

I only had a couple of problems.

1 ICU 50 didn't support Windows 2000.
===================
ICU 50 uses GetGeoInfoW
https://github.com/unicode-org/icu/blob/4509ab7d96fe996d528ce5db650a031cefee7435/icu4c/source/common/wintz.cpp#L71
GetGeoInfoW :  Minimum supported client  Windows XP
https://msdn.microsoft.com/en-us/windows/desktop/dd318099?f=255&MSPPError=-2147217396
ICU 49 works.
I changed only two lines in gnustep source.
instead 949 and 950 lines
https://github.com/gnustep/libs-base/blob/ea95ff1f59e087e982edadbf5df21a76fc5e774a/Source/NSDateFormatter.m#L949
https://github.com/gnustep/libs-base/blob/ea95ff1f59e087e982edadbf5df21a76fc5e774a/Source/NSDateFormatter.m#L950
I used:
```cpp
timeStyle = NSToUDateFormatStyle (internal->_timeStyle);
dateStyle = NSToUDateFormatStyle (internal->_dateStyle);
```

2 Configure issues
===================
I changed configure here and in libs-gui to work with icu 49.
instead of harcoded libs (https://github.com/gnustep/libs-gui/blob/master/configure.ac#L464) I used pkg-config

3 Themes didn't work on Windows 2000
===================
The issue because Windows 2000 doesn't have uxtheme.dll.
But I found the site: https://kzar.co.uk/blog/2010/10/06/fixing-spotify-uxtheme.dll-error-on-windows-2000/
It works with the dll.

>Give us feedback!   Tell us what you like; tell us what you think could be better.

Thank you, few toolkits work in 2019 on Windows 2000.

I saw that: https://groups.google.com/forum/#!topic/gnu.gnustep.discuss/d4CSDyz29Rk

I don’t know if ifdef is needed in your code, maybe such a note will be enough for those who need to build gnustep to work on Windows 2000

I built gnustep with support Windows 2000 just for fun, not for real need.

**Comment by ivucica** [comment]
Thank you!

I would be happy to merge 1 as is, as it seem innocuous enough, if provided
as a pull request.

I would be happy to merge 2 with #ifndef UDAT_PATTERN.

I don't think we can address 3 ourselves, but winux theme is optional
anyway.

We are, of course, unlikely to actively support Windows 2000, because I
don't think any of us uses Windows 2000, and setting up CI would be very
difficult as well.

>

**Comment by fsb4000** [comment]
>We are, of course, unlikely to actively support Windows 2000, because I don't think any of us uses Windows 2000, and setting up CI would be very difficult as well.

Sure, it's just usually helpful to know which latest version is supported for a specific operating system.
Does anyone else remember which version of the latest supported Windows 9x?
Perhaps it would be useful to indicate on the site...

Similar to https://gtk-win.sourceforge.io/home/index.php/Main/Downloads

**Comment by fsb4000** [comment]
Actually I don't know how to fix libs-gui in configure...

Libs-gui correctly takes data from icu-config

But icu-config gives the wrong ones (I don't have -licudata)

For myself, I fixed the already generated makefile, which is not suitable for the github version.

Perhaps there is nothing to fix on the side of libs-gui, and apply a patch for icu-config...


https://imgur.com/a/wESeQpo
