### ISSUE TITLE
-[NSNotificationCenter addObserverForName:object:queue:usingBlock:] has a leak

### ISSUE THREAD

**Issue by lcampbel** [gnustep/libs-base#360]
I believe

`  return observer;
`

should be

`  return AUTORELEASE(observer);
`

**Comment by rfm** [comment]
> On 4 Jan 2024, at 18:55, Larry Campbell ***@***.***> wrote:
> 
> 
> I believe
> return observer;
> should be
> return AUTORELEASE(observer);

Thanks, I changed that as suggested.
