### ISSUE TITLE
Exception when initializing NSLocale with dash-separated identifier

### ISSUE THREAD

**Issue by triplef** [gnustep/libs-base#368]
Some systems (like Android) seem to return dash-separated locale identifiers like `en-US` instead of `en_US`. Initializing NSLocale with such an identifier results in an exception in `NSLocale.m:285` because the result of `[result rangeOfString: @"_"]` is not checked for `NSNotFound`:

https://github.com/gnustep/libs-base/blob/f7eff46e86411ae09d0b2d7b669cfa7a35d5bed0/Source/NSLocale.m#L275-L285

Exception:
> NSRangeException, reason: in deleteCharactersInRange:, range { 2, 9223372036854775805 } extends beyond size

I’m not sure which kind of identifiers this code is supposed to handle, but I think it’s at least missing some validation checking.

**Comment by rfm** [comment]
I added some code to avoid the exception and (hopefully) implement the intention suggested by the existing comments.
