### ISSUE TITLE
Linker error clang-8

### ISSUE THREAD

**Issue by yobson** [gnustep/libs-base#39]
I've tried to build this on two platforms with clang 8 and both failed for the same reason. I get the following linker error:
```bash
 Linking subproject Additions ...
clang-8: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
/usr/bin/ld: -r and -pie may not be used together
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [/usr/local/share/GNUstep/Makefiles/Instance/subproject.make:61: obj/subproject.o] Error 1
make[3]: *** [/usr/local/share/GNUstep/Makefiles/Instance/subproject.make:45: internal-subproject-all_] Error 2
make[2]: *** [/usr/local/share/GNUstep/Makefiles/Master/rules.make:297: Additions.all.subproject.variables] Error 2
make[1]: *** [/usr/local/share/GNUstep/Makefiles/Master/serial-subdirectories.make:53: internal-all] Error 2
make: *** [/usr/local/share/GNUstep/Makefiles/Master/serial-subdirectories.make:53: internal-all] Error 2
```
It's the same on both platforms. The two platforms are:
- Manjaro Linux
- Termux (android)

I was just following [these](http://wiki.gnustep.org/index.php/Building_GNUstep_with_Clang) instructions both times.

Thanks for your time!
James

**Comment by yobson** [comment]
I've worked it out! Both systems enforce PIE (I think? I know android does now) and the gnustep-make config incorrectly uses `-Wl,-r` instead of `-r`. I'll admit I have no idea why or how to make a fix but I thought you should know. I hear PIE by default is in fashion!

**Comment by yobson** [comment]
Well. I'm getting seg faults in all graphical applications now. Might not be related, but maybe this linking change has made a difference!

**Comment by AlessandroSangiuliano** [comment]
On Manjaro I solved (work around, was Genuary I think)  passing -no-pie at build time.

Try it because i don't remember if it was sufficient.

**Comment by triplef** [comment]
This should be fixed with the latest GNUstep Make via this change that removes the `-r` flag when linking:
https://github.com/gnustep/tools-make/commit/ce9d4f5526d29d45912c830bd544b39998fabe5e
