### ISSUE TITLE
dispatch cannot be used

### ISSUE THREAD

**Issue by pangdahua** [gnustep/libs-base#4]
Os:Centos 6.7
Is there any way to using dispatch on centos or change os to ubuntu or freebsd!

thanks!

**Comment by zenny-chen** [comment]
Grand Central Dispatch is independent of Objective-C. It is a C-based library. You may search 'libdispatch' to use it.

**Comment by ivucica** [comment]
Indeed -- libdispatch is something independent, and I'll close this unless you can point to how the inquiry relates to GNUstep Base.

This is also not a venue for development assistance or general discussion -- we have mailing lists for that. Feel free to mail there with a specific GNUstep-related inquiry.
