### ISSUE TITLE
Crash when calling NSUndoManager with method returning object

### ISSUE THREAD

**Issue by triplef** [gnustep/libs-base#456]
Using libobjc2 and ARC, the following code crashes in `objc_retainAutoreleasedReturnValue` because the call to `returnValue:` on NSUndoManager doesn’t actually return a value (NSUndoManager just caches the invocation using `forwardInvocation:`).

I’m not sure if this is a runtime, codegen, or libs-base issue. @davidchisnall any thoughts?

```objc
- (void)testUndoManager
{
	NSUndoManager *undoManager = [[NSUndoManager alloc] init];

	[[undoManager prepareWithInvocationTarget:self] returnValue:[[NSObject alloc] init]];
}

- (id)returnValue:(id)value
{
	return value;
}
```

```assembly
    0x77dc62c258 <+840>:  add    x1, x1, #0xe78
    0x77dc62c25c <+844>:  bl     0x77dd42ea10              ; symbol stub for: objc_msgSend
    0x77dc62c260 <+848>:  mov    x29, x29
    0x77dc62c264 <+852>:  bl     0x77dd42ea20              ; symbol stub for: objc_retainAutoreleasedReturnValue
->  0x77dc62c268 <+856>:  bl     0x77dd42ea30              ; symbol stub for: objc_release
```

**Comment by triplef** [comment]
The way NSUndoManager works it just [stores the invocation](https://github.com/gnustep/libs-base/blob/4f0a8d60c2d4fa30e76fd7e8bf3752c1ce59a41b/Source/NSUndoManager.m#L454) for later use to be executed *if* an undo is performed. So at the time of the crash the NSInvocation is not actually invoked.

**Comment by davidchisnall** [comment]
(Getting this right is hard and is part of the reason that Apple encourages you to use blocks, rather than the forward-invocation model, undo now)

**Comment by rfm** [comment]
I think there's a compiler error in the example: the return value is unused so the compiler should not be emitting code to retain it.
I think that should always be the case for proper usage of NSUndoManager, however I agree that the base library implementation should set the invocation return value to zeros as a matter of safer coding.

**Comment by davidchisnall** [comment]
> I think there's a compiler error in the example: the return value is unused so the compiler should not be emitting code to retain it.

It isn't.  It's emitting code to prevent it from propagating in the autorelease pool.  The first call removes it from the top of the autorelease pool and retains it.  The second releases it.  This ensures that its lifetime is not accidentally extended by being an unused autoreleased object.

> I think that should always be the case for proper usage of NSUndoManager, however I agree that the base library implementation should set the invocation return value to zeros as a matter of safer coding.

The compiler does not know anything about `NSUndoManager`, it knows that this method is declared as returning `id`.  As such, it assumes that the value in the return register is either a pointer to a valid object or nil.  The GNUstep implementation of `NSUndoManager` is violating this contract.

**Comment by rfm** [comment]
I modified NSUndoManager in base.

**Comment by rfm** [comment]
Thanks for that ... I was under the impression that the compiler emitted the code to call objc_retainAutoreleasedReturnValue() rather than relying on objc_msgSend() to do it.

**Comment by triplef** [comment]
Thank you both for the quick feedback and fix!

I haven’t had a chance to try it out yet, but if I understand this correctly [this change](https://github.com/gnustep/libs-base/commit/156be3ad53461aaf556c8f62543ff36b877509e7#diff-250f5938c8c01b0c9bcfbb992a76e3ac55fd5b4ac28b4147b794f08ee3668e6b) should fix it, although ideally we should always zero out the return value of NSInvocation instances instead of just in this special case? Guess it would be good for us to add a test for this too.
