### ISSUE TITLE
Crash after changes to NSDate to make it into a small object, issue with services menu infinite recursion...

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-base#457]
I will add details here from the other comments and anything else that has been discussed...

**Comment by rfm** [comment]
So, it's a subtle issue which is impossible to fix: we either don't use tiny objects for dates, or we change code which no longer works.

Arguably it's the gui code which is buggy here, though the documentation of -earlierDate: and -laterDate: certainly suggests that the way the gui uses them is reasonable 

The workaround/fix is to replace code of the form
  if ([receiver earlerDate: other] == other)
with
    if ([receiver earlerDate: other] != receiver)

So I'm inclined to say that we should change the calling code.

**Comment by rfm** [comment]
Sorry, example problem/workaround wrong, but you know what I meant :-)
  

  

  

  
  
  
  
  
>

**Comment by rfm** [comment]
I have committed the fix to the GUI.

I'm inclined to restore a modified version of NSDate.m with formatting tweaks and the minor fixes to return the receiver when receiver and argument have the same values.

**Comment by gcasa** [comment]
> Sorry, example problem/workaround wrong, but you know what I meant :-)
> […](#)
> On 31 Oct 2024 at 18:26, rfm ***@***.***> wrote: So, it's a subtle issue which is impossible to fix: we either don't use tiny objects for dates, or we change code which no longer works. Arguably it's the gui code which is buggy here, though the documentation of -earlierDate: and -laterDate: certainly suggests that the way the gui uses them is reasonable The workaround/fix is to replace code of the form if ([receiver earlerDate: other] == other) with if ([receiver earlerDate: other] != receiver) So I'm inclined to say that we should change the calling code. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Yep, absolutely.  I really think we should get some app tests into base as it would have caught this.   I just tested the reinstatement of the code and your GUI fix.  Awesome.   I will close this issue.

**Comment by rmottola** [comment]
I was away from the computers where I tested over the past days. I could only test on my laptop and a Raspberry and things look improved.
I will retest more thoroughly next week on systems where it was proven to be wrong (since it  strangely wasn't reproducible on all systems!)
