### ISSUE TITLE
@interface NSCoder (NSGeometryKeyedCoding) is already there

### ISSUE THREAD

**Issue by Matvii-Jarosh** [gnustep/libs-base#469]
The MISSING file says that it is not implemented, but it is already implemented in `NSKeyedArchiver`, but `@interface NSCoder (NSGeometryCoding)` is not implemented. I looked and the implementation of `NSGeometryCoding` has been around for 21 years. I think it should be transferred to NSCoder files if necessary. I’m just notifying you about this, I don’t think it could be an error, but I can’t help but tell you

**Comment by Matvii-Jarosh** [comment]
Hmm, I looked later and found that NSGeometry is almost completely implemented except for valueWithEdgeInsets and edgeInsetsValue. Yesterday I tried to add them but it was a little tricky, I think I’ll try again today

**Comment by rfm** [comment]
I agree, most of the implementation has been there pretty much forever (the exception being a few methods added by Apple relatively recently).
I don't know whether the interface declaration NSCoder(NSGeometryCoding) was added by Apple more recently than the method implementations or if it has always been there but was done differently in base by accident or for some reason.
In any case, I see no reason not to add the interface.
