### ISSUE TITLE
Crash on launch due to recursive NSUserDefaults/NSBundle initialization

### ISSUE THREAD

**Issue by triplef** [gnustep/libs-base#471]
With a [recent change](https://github.com/gnustep/libs-base/commit/e64b7dc6b3442828eac447880ab058fabefab835), `+[NSUserDefaults initialize]` now calls `GSPrivateInfoDictionary()` to get the bundle identifier. However, loading the info dictionary can itself call into NSUserDefaults, which causes a nil bundleIdentifier to be added to the search list, leading to an exception being thrown at initialization.

This can happen with different stack traces:
<img width="615" alt="image" src="https://github.com/user-attachments/assets/3db92657-cfa7-4ece-b570-b5c528ef4388">
<img width="812" alt="image" src="https://github.com/user-attachments/assets/d0bd47e3-3d6b-430a-984a-74cbde0fc66f">

**Comment by triplef** [comment]
@rfm would be great to get your thoughts on how to best fix this.

**Comment by rfm** [comment]
GSPrivateInfoDictionary() should not need to initialize NSUserDefaults.
I fixed the unnecessary call from GSMimeDocument and, hopefully (I don't have an android system to test on) the issues in the android strartup code.
Is it still an issue with the latest code in git master?

**Comment by triplef** [comment]
Thanks, I’ll give it a try.

What about NSLog being called along the way initializing NSUserDefaults (see first screenshot above)?

**Comment by triplef** [comment]
Btw. this happens for me on both Android (top screenshot) and Windows (bottom screenshot), but might depend on how the app is initialized exactly.

**Comment by rfm** [comment]
Well NSLog() shouldn't be called while initialising... On Android it was being called because there was system specific code trying to append a path extension to an empty string... I hope I've added all necessary checks to prevent that.
  

  

  

  
  
  
  
  
>

**Comment by rfm** [comment]
Actually, we should probably try to bomb-proof NSLog and NSException to avoid recursion somehow.
  

  

  

  
  
  
  
  
>

**Comment by triplef** [comment]
I can confirm that our app now launches on Windows and Android with the latest changes, thanks for the fix.

I think proofing NSLog and NSException would be a great idea, as it seems difficult to exclude any possibility of them being called during initialization.

**Comment by triplef** [comment]
Unfortunately I spoke a bit too soon... our app is still crashing on launch on Windows in some cases.

Specifically, if the app is launched by our Windows CI service (i.e. without an interactive session / screen attached) it crashes on launch with these logs and stack trace using libs-base @ a1a3f42ec (i.e. with your recent fixes to avoid recursion with NSLog):

```
GSPrivateDefaultsFlag() called within +[NSUserDefaults initialize] always returns NO.
GSPrivateDefaultsFlag() called within +[NSUserDefaults initialize] always returns NO.
Uncaught exception NSInvalidArgumentException, reason: Tried to add nil key to dictionary
```

<img width="950" alt="image" src="https://github.com/user-attachments/assets/4002a965-7de0-4ee1-ae02-dc32c5217d0b">

I’m not fully sure what’s going on, but I think first `GSPrivateExecutablePath()` is asserting because it’s unable to find a path (not sure why?), and then that leads to another `NSLog()` call which somehow leads to something trying to add a nil key to a dictionary.

I’d appreciate if you could take another look @rfm.

**Comment by rfm** [comment]
I added some diagnostic logging to try to see why it's failing to find the executable path.  Please see what output and stack trace that produces.

**Comment by triplef** [comment]
Thanks! Here are the new logs and stack trace:
```
Unable to get absolute value of executable path 'build\MyApp.exe'.
GSPrivateDefaultsFlag(3) called within +[NSUserDefaults initialize] always returns NO.
GSPrivateDefaultsFlag(4) called within +[NSUserDefaults initialize] always returns NO.
Uncaught exception NSInvalidArgumentException, reason: Tried to add nil key to dictionary
```
<img width="683" alt="image" src="https://github.com/user-attachments/assets/dc4dddd9-9b3f-4738-80ff-b0cd95a35b26">

Additionally we’re now getting this exception on launch on Android (after we call `GSInitializeProcessAndroid()`):
```
NSBundle.m:1861  Assertion failed in NSBundle(instance), method mainBundle.  NSInternalInconsistencyException
```
<img width="628" alt="image" src="https://github.com/user-attachments/assets/4ad7efd5-79f7-4b24-9e17-b58ca591f493">

**Comment by rfm** [comment]
I can't reproduce the issue, but it's clearly because the path of the executable can't be determined for some reason.
If you can find out what that reason is we can address it.
I have added debug logs in the function that tries looking in the PATH for the executable ... it should at least show us where the code is looking..

**Comment by triplef** [comment]
I think I was able to track down both issues.

The "Tried to add nil key to dictionary" exception happens if NSLog is called somewhere in the initialization again, which causes `[_persDomains setObject: pd forKey: bundleIdentifier]` to be called with a nil bundleIdentifier. I guess we just need to add more safety here?
<img width="438" alt="image" src="https://github.com/user-attachments/assets/721e3cab-72c4-44b7-ab5d-aa09ea23b0b9">

The crash on Android happens due to this change from yesterday, which causes `_find_main_bundle_path()` to return an empty string:
https://github.com/gnustep/libs-base/commit/e7dd2f741a905ea487b79f2ff1e2ce1b265cd8ca#diff-17196bdb008a40fd406c40f5b598514758aafe830fc8fc8395e6dcc2b658e5c6R508

**Comment by triplef** [comment]
Additionally the two Android-specific methods `-[NSBundle assetForPath:withMode:]` and `-[NSBundle assetDirForPath:]` need added safety to protect against resourcePath being nil, as they can be called as part of GSPrivateInfoDictionary() before NSBundle is initialized, otherwise they can throw an exception from calling hasPrefix: with a nil parameter.

**Comment by triplef** [comment]
Thanks, Android is working now but Windows is still crashing.

I think what happens is that `AbsolutePathOfExecutable()` is being called without NSBundle being initialized, causing `_launchDirectory` to be nil. Maybe we just need to call `[NSBundle class]` somewhere in `AbsolutePathOfExecutable()`?

```
AbsolutePathOfExecutable() failed to get launch directory for 'build\MyApp.exe'.
GSPrivateDefaultsFlag(3) called within +[NSUserDefaults initialize] always returns NO.
GSPrivateDefaultsFlag(4) called within +[NSUserDefaults initialize] always returns NO.
GSPrivateDefaultsFlag(3) called within +[NSUserDefaults initialize] always returns NO.
GSPrivateDefaultsFlag(4) called within +[NSUserDefaults initialize] always returns NO.
GSPrivateDefaultsFlag(0) called within +[NSUserDefaults initialize] always returns NO.
GSPrivateDefaultsFlag(2) called within +[NSUserDefaults initialize] always returns NO.
NSBundle.m:1884  Assertion failed in NSBundle(instance), method mainBundle.  NSInternalInconsistencyException
```

**Comment by rfm** [comment]
That seems plausible, but the point of the code is to try to avoid crashes due to interdependencies of classes during initiailsation, so we want to avoid initialising NSBundle.  So, we need to make sure _launchDirectory is set up before NSBundle is initialised (rather than initialising NSBundle earlier).
Does my latest change to do that fix things?

**Comment by triplef** [comment]
Yes that did it. Thank you.

**Comment by rfm** [comment]
Great to hear.  Thanks for all your help.
