### ISSUE TITLE
NSNotificationCenter should automatically unregister released observers

### ISSUE THREAD

**Issue by triplef** [gnustep/libs-base#481]
On newer Apple OS releases, NSNotificationCenter no longer requires users to unregister observers that get released. It would be helpful if GNUstep could do the same.

> If your app targets iOS 9.0 and later or macOS 10.11 and later, you do not need to unregister an observer that you created with this function. If you forget or are unable to remove an observer, the system cleans up the next time it would have posted to it.

https://developer.apple.com/documentation/foundation/nsnotificationcenter/1415360-addobserver?language=objc

**Comment by triplef** [comment]
Thanks for your feedback @rfm. I’m not familiar with what weak reference support looks like with GCC, but since this is a new-ish feature on Apple platforms as well, wouldn’t it be ok to support it with libobjc2 only if it’s only feasible there? I see this as an improved implementation, similar to the new KVO implementation that also requires runtime features. Normal add/remove observer would of course still work with all runtimes.

For us the main reason we’d like to see this in GNUstep is that our devs mainly write code on Apple platforms, and if they forget to remove an observer somewhere we won’t notice on those platforms, plus it’s often difficult to catch these mistakes as the app might not crash immediately if the observer is released. Having this work the same across (our) platforms would eliminate this potential source of errors.

**Comment by rfm** [comment]
I'd be very happy to see a contribution of (1) above, since that would also allow us to fix weak pointer based incompatibilities elsewhere in base,  I think a C language implementation based on the algorithms in arc.mm in libobjc2 would be great for portability.

**Comment by rfm** [comment]
Actually, I think I'll look into adding weak reference support (emulation of the runtime features) for use with gcc and the gnu runtime anyway, because having working weak pointer versions of NSPointerArray, NSHashTable and NSMapTable would be good.

**Comment by triplef** [comment]
Great, thank you.

**Comment by rfm** [comment]
I have preliminary (working) code for weak references with gcc in a new 'weakref' branch.  As far as I know the only problem with it is that it's currently going to be too slow because every object deallocation involves locking and a hash table lookup.  In libobjc2 this is mostly avoided by marking each weakly referenced object, and using a lock-free check at deallocation to see whether the object being deallocated has weak references.  Probably we need something similar.

**Comment by rfm** [comment]
This should now be working on the 'weakref' branch for both the classic gnu runtime and for the modern ruuntime.
There are even some new testcases :-)

**Comment by triplef** [comment]
Thank you Richard, that’s great!
