### ISSUE TITLE
NSDictionary keysSortedByValueUsingComparator: does not return keys sorted by the corresponding value in the dictionary

### ISSUE THREAD

**Issue by plaurent** [gnustep/libs-base#69]
NSDictionary keysSortedByValueUsingComparator: appears to have a bug.  It does not actually return the keys sorted by the values.  (Instead it appears to be sorting the keys based on their own value rather than the value each maps to in the dictionary...)

A test illustrating the failure is provided as part of https://github.com/gnustep/libs-base/pull/68

For reference here is what Apple's docs say
"keysSortedByValueUsingComparator:
Returns an array of the dictionary’s keys, in the order they would be in if the dictionary were sorted by its values using a given comparator block."

**Comment by rfm** [comment]
Fixed in trunk
