### ISSUE TITLE
Error using __block storage type modifier due to NSXPCConnection.h undefining it

### ISSUE THREAD

**Issue by triplef** [gnustep/libs-base#97]
With the [recent change in NSXPCConnection](https://github.com/gnustep/libs-base/commit/0cd9843f5f40e7262cf9d41bccf022a3b0b5a371#diff-273991c79ee8bf6242b483d51b0cec60) I am no longer able to use the `__block` storage type modifier on variable definitions, because the change is undefining the `__block` built-in.

When I remove the #ifdef/#undef in NSXPCConnection.h, I get the following output showing the original built-in definition:
```
NSXPCConnection.h:41:9: warning: '__block' macro redefined [-Wmacro-redefined]
#define __block __gs_unistd_block
        ^
<built-in>:66:9: note: previous definition is here
#define __block __attribute__((__blocks__(byref)))
```

This is using the Android toolchain with the 2.0 runtime and blocks.

**Comment by rfm** [comment]
> On 11 Feb 2020, at 16:54, Frederik Seiffert <notifications@github.com> wrote:
> 
> With the recent change in NSXPCConnection I am no longer able to use the __block storage type modifier on variable definitions, because the change is undefining the __block built-in.
> 
> When I remove the #ifdef/#undef in NSXPCConnection.h, I get the following output showing the original built-in definition:
> 
> NSXPCConnection.h:41:9: warning: '__block' macro redefined [-Wmacro-redefined]
> #define __block __gs_unistd_block
>         ^
> <built-in>:66:9: note: previous definition is here
> #define __block __attribute__((__blocks__(byref)))
> 
> This is using the Android toolchain with the 2.0 runtime and blocks.

I removed both unistd.h and the workaround for the clash between it and clang.
If we find systems where sys/types.h doesn't have all the typdefs this file needs, I guess we will have to have system-dependent macros to declare types in cases where the system headers clash with clang.

**Comment by triplef** [comment]
Thanks @rfm. I’ll give it a try once you push the fix.

**Comment by triplef** [comment]
Fixed by https://github.com/gnustep/libs-base/commit/c8cfcec652cba1402cfb61aea9668a8805d1a59a. 👍
